### PR TITLE
Refactor Bearer Auth

### PR DESCRIPTION
**Pull request by gevorgmansuryan**

### CODE REVIEW

**Review by luke- — CHANGES_REQUESTED** [review]
@gevorgmansuryan Thanks, looks very good!

The current admin config is already very overloaded as we have a many options here. What do you think about splitting/rebuilding it a bit

E.g.

- Tabs for the different features
    - General (Enabled Users)
    - Authentication
    - Modules

- Maybe we can leave out the checkbox for "Bearer Auth". If no tokens have been created, it is not active. 

- Maybe don't auto generate JWT Key. And leave empty for disable JWT Auth.  

--- 

Other points:

- Adjust documentation for new auths
- Tests for different auths

**Comment by gevorgmansuryan** [comment]
Okay Will be done. What if we make jwt auth configurable and add enableJwtAuth checkbox like others?

**Comment by luke-** [comment]
@gevorgmansuryan Thanks, looks really nice.

Here some points:
image
image
image

Tests & Swagger Docs would also be good, especially for the tokens.

**Comment by gevorgmansuryan** [comment]
@luke- `Enabled users` used for JWT auth only.

**Comment by luke-** [comment]
@gevorgmansuryan 

> @luke- `Enabled users` used for JWT auth only.

This means that with Basic Auth all users are currently always enabled? I think it would be good to change this, and with authentication by Username & Password (Basic Auth & JWT), always allow the activated users or if checked all users.

**Comment by gevorgmansuryan** [comment]
@luke- 

> This means that with Basic Auth all users are currently always enabled?
Yes, it's always worked in this way

Okay Will add user check for Basic Auth too, + hint

**Comment by gevorgmansuryan** [comment]
@luke- 
> query param auth

Yes. It will work when bearer auth is enabled. 
When bearer auth checkbox is unchecked it will uncheck too. It is not possible to check query param auth checkbox without checking bearer auth checkbox

**Comment by gevorgmansuryan** [comment]
@luke- 
8F0FACAB-43C5-48FC-9107-3ADDC44EC5AB

**Comment by luke-** [comment]
@gevorgmansuryan Can you please check the tests?

Currently only this test should fail: https://github.com/humhub/rest/issues/114

**Review by luke- — APPROVED** [review]

**Review by luke- — APPROVED** [review]

**Review by luke- — APPROVED** [review]

**Pull request merged**
